name: Build and Deploy

on:
  # push:
  #   branches: [ "master" ]
  workflow_dispatch:

env:
  NETCORE_VERSION: "9.0.x"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Ensure this is checkout, not setup-dotnet
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Publish
        run: dotnet publish ./src/SimpleUITemplates.UI/SimpleUITemplates.UI.csproj -c Release -o ./publish/wwwroot

      - name: Modify base href for GitHub Pages
        run: |
          # Replace the base href in the index.html file to point to the repository
          sed -i 's|<base href="/">|<base href="/<your-repo-name>/">|' /home/runner/work/simple-ui-templates/simple-ui-templates/publish/wwwroot/index.html

      - name: Add .nojekyll file
        run: |
          # Create the .nojekyll file to disable Jekyll processing on GitHub Pages
          touch /home/runner/work/simple-ui-templates/simple-ui-templates/publish/wwwroot/.nojekyll

      - name: Copy index.html to 404.html 📄
        run: |
          cp /home/runner/work/simple-ui-templates/simple-ui-templates/publish/wwwroot/index.html /home/runner/work/simple-ui-templates/simple-ui-templates/publish/wwwroot/404.html  

      - name: Deploy to gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./publish/wwwroot  # Fixed folder path here
